### ISSUE TITLE
Take this down

### ISSUE THREAD

**Issue by monkxy** [Crazygird/BlookHax#1]
woops wrong repo

**Comment by Crazygird** [comment]
??

**Comment by monkxy** [comment]
> ??

made this issue on the wrong repo sorry.

**Comment by Crazygird** [comment]
your cheats are great btw

**Comment by monkxy** [comment]
> your cheats are great btw

Ty

**Comment by Crazygird** [comment]
my friend is addicted to them

**Comment by Crazygird** [comment]
but then he got caught
